In [1]:
import pandas as pd
import os

BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), "../../"))

In [2]:
data_path = os.path.join(BASE_DIR, "data/raw/data.csv")

data = pd.read_csv(data_path)

In [3]:
data

                                                Sentence    Emotion
0              giảng_viên nhiệt_tình giúp_đỡ sinh_viên .     Vui vẻ
1              tài_liệu ôn_tập thi không được cung_cấp .   Tức giận
2      mọi tờ lịch trong phòng tôi đều bị gạch chéo v...     Sợ hãi
3             cách_thức diễn_đạt chưa đạt hiệu_quả tốt .   Tức giận
4                    cùng sinh_viên giải nhiều bài_tập .     Vui vẻ
...                                                  ...        ...
28731                           giọng thầy khó nghe rõ .  Trung lập
28732                               tao nhìn thấy thèm 🤣     Vui vẻ
28733  nội_dung thực_hành chỉ là copy và paste , chưa...  Trung lập
28734  trước khi lấy vợ boss có một thân hình hoàn mĩ...    Buồn bã
28735                           có chút không hiểu bài .    Buồn bã

[28736 rows x 2 columns]

In [4]:
data['Emotion'] = data['Emotion'].str.strip().str.replace('"', '')

data['Emotion'] = data['Emotion'].replace({
    ' Vui vẻ': 'Vui vẻ',
    ' Trung lập': 'Trung lập',
    ' Tức giận': 'Tức giận',
    ' Buồn bã': 'Buồn bã',
    ' Sợ hãi': 'Sợ hãi',
    '"Vui vẻ"': 'Vui vẻ',
    '"Tức giận"': 'Tức giận',
    '"Buồn bã"': 'Buồn bã',
    '"Sợ hãi"': 'Sợ hãi'
})

In [5]:
data['Emotion'].value_counts()

Emotion
Vui vẻ       9595
Trung lập    5509
Sợ hãi       5203
Tức giận     4255
Buồn bã      4174
Name: count, dtype: int64

In [6]:
data_path = os.path.join(BASE_DIR, "data/raw/data.csv")

data.to_csv(data_path, index=False)

In [7]:
df_shuffled = data.sample(frac=1, random_state=42).reset_index(drop=True)

data_suffled_path = os.path.join(BASE_DIR, "data/raw/data.csv")

df_shuffled.to_csv(data_suffled_path, index=False)

In [8]:
data = pd.read_csv(data_path)
data['Emotion'].value_counts()

Emotion
Vui vẻ       9595
Trung lập    5509
Sợ hãi       5203
Tức giận     4255
Buồn bã      4174
Name: count, dtype: int64

# Chuẩn hóa nhãn thành sốsố

In [9]:
label_mapping = {
    "Vui vẻ": 0,
    "Tức giận": 1,
    "Buồn bã": 2,
    "Sợ hãi": 3,
    "Trung lập": 4
}

data["Label"] = data["Emotion"].map(label_mapping)
data = data.drop(columns=["Emotion"])
data

                                                Sentence  Label
0               em thấy mình như chiếc lá bị gió cuốn đi      2
1      dễ thương ghê =)) nói y như mấy ông ngồi nhậu ...      0
2      cách chấm điểm giữa các nhóm chưa được công_bằ...      1
3       đề làm thực_hành thực_sự chỉ dễ cho giảng_viên .      1
4          giảng_viên nên cũng cấp slide cho sinh_viên .      4
...                                                  ...    ...
28731  em sợ giảng viên sẽ không cho em cơ hội bảo vệ...      3
28732    vừa nghe thấy tiếng rít như móng tay cào vào gỗ      3
28733  mong anh có thể đạt được ước mơ của mình .... ...      0
28734       nhiệt_tình , vui_vẻ hòa đồng với sinh_viên .      0
28735                      nào thức tỉnh đi các bạn ơi 😃      4

[28736 rows x 2 columns]

# Loại bỏ ký tự đặc biệt, số và khoảng trắng thừa

In [10]:
import re

def clean_text(text):
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"[^\w\s]", "", text)
    return text

data["Sentence"] = data["Sentence"].astype(str).apply(clean_text)
data

                                                Sentence  Label
0               em thấy mình như chiếc lá bị gió cuốn đi      2
1      dễ thương ghê  nói y như mấy ông ngồi nhậu tro...      0
2      cách chấm điểm giữa các nhóm chưa được công_bằng       1
3        đề làm thực_hành thực_sự chỉ dễ cho giảng_viên       1
4           giảng_viên nên cũng cấp slide cho sinh_viên       4
...                                                  ...    ...
28731  em sợ giảng viên sẽ không cho em cơ hội bảo vệ...      3
28732    vừa nghe thấy tiếng rít như móng tay cào vào gỗ      3
28733   mong anh có thể đạt được ước mơ của mình  cố lên      0
28734         nhiệt_tình  vui_vẻ hòa đồng với sinh_viên       0
28735                       nào thức tỉnh đi các bạn ơi       4

[28736 rows x 2 columns]

# Tokenize

In [11]:
import torch
from torch.utils.data import TensorDataset
from transformers import AutoTokenizer
from underthesea import word_tokenize
from pyvi import ViTokenizer

def hybrid_tokenize(text):
    underthesea_tokens = word_tokenize(text, format="text").split() 
    pyvi_tokens = ViTokenizer.tokenize(text).split()
    
    merged_tokens = []
    
    i, j = 0, 0
    while i < len(underthesea_tokens) and j < len(pyvi_tokens):
        ut_token = underthesea_tokens[i]
        pv_token = pyvi_tokens[j]

        if ut_token == pv_token:
            merged_tokens.append(ut_token)
            i += 1
            j += 1
        else:
            if len(ut_token) >= len(pv_token):
                merged_tokens.append(ut_token)
                i += 1
                j += len(pv_token.split('_'))
            else:
                merged_tokens.append(pv_token)
                j += 1
                i += len(ut_token.split('_'))
    
    merged_tokens += underthesea_tokens[i+1:] + pyvi_tokens[j+1:]
    return merged_tokens

text = "Tôi cảm thấy cô đơn trong cuộc sống này"
merged_tokens = hybrid_tokenize(text)
print("Merged Tokens:", merged_tokens)

e:\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Merged Tokens: ['Tôi', 'cảm_thấy', 'cô_đơn', 'trong', 'cuộc_sống', 'này']

In [15]:
from sklearn.model_selection import train_test_split

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def tokenize_data(df):
    tokenized_texts = []
    # attention_masks = []
    labels = []
    
    for index, row in df.iterrows():
        text = row['Sentence'] 
        label = row['Label']  
        merged_tokens = hybrid_tokenize(text)
        encoding = tokenizer(' '.join(merged_tokens), truncation=True, padding="max_length", max_length=256, return_tensors="pt")
        tokenized_texts.append(encoding["input_ids"][0])
        # attention_masks.append(encoding["attention_mask"][0])  
        labels.append(label)

    input_ids = torch.stack([torch.tensor(tokens) for tokens in tokenized_texts])
    # attention_mask = torch.stack([torch.tensor(mask) for mask in attention_masks]) 
    labels = torch.tensor(labels)
    
    return TensorDataset(input_ids, labels)

train_df, test_df = train_test_split(data, test_size=0.2, stratify=data["Label"], random_state=42)
valid_df, test_df = train_test_split(test_df, test_size=0.5, stratify=test_df["Label"], random_state=42)

train_data = tokenize_data(train_df)
valid_data = tokenize_data(valid_df)
test_data = tokenize_data(test_df)

output_dir = os.path.join(BASE_DIR, "data/processed")
os.makedirs(output_dir, exist_ok=True)

torch.save(train_data, os.path.join(output_dir, "train.pt"))
torch.save(valid_data, os.path.join(output_dir, "valid.pt"))
torch.save(test_data, os.path.join(output_dir, "test.pt"))

C:\Users\TGDD\AppData\Local\Temp\ipykernel_2752\1031840982.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input_ids = torch.stack([torch.tensor(tokens) for tokens in tokenized_texts])